
version: '3'

services:
 app:
   build:
    context: .
   image:
      pwa_images
   ports:
     - "8000:8000"
   volumes:
     - ./app:/app
   stdin_open: true
   tty: true
   command: >
     sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runsslserver 0.0.0.0:8000"